blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("post/<int:id>/", views.post, name="post"),

]

jobs/urls.py
# noqa: D100
from django.urls import path
from . import views
app_name = "jobs"

urlpatterns = [
    path("add/", views.job_add_view, name="add"),
    path("archive/", views.JobArchiveView.as_view(), name="archive"),
    path("delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete"),
    path("download/", views.job_download_view, name="download"),
    path("edit/<int:pk>/", views.job_edit_view, name="edit"),
    path("list/", views.JobListView.as_view(), name="list"),
    path("settings/", views.settings_view, name="settings"),
]

jobs/models.py
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils import timezone

from accounts.models import Profile
from core.models import (
    Country,
    Currency,
    JobFunction,
    LocationPolicy,
    WorkContract,
    PayRate,
)

from core.choices import StatusChoices, SourceChoices

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create your models here.


class Job(models.Model):
    id = models.BigAutoField(primary_key=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    url = models.URLField(blank=True, null=True)
    source = models.CharField(
        max_length=2, choices=SourceChoices.choices(), null=True, blank=True
    )

    job_title = models.CharField(max_length=100, blank=True, null=True)
    job_function = models.ForeignKey(
        JobFunction, on_delete=models.SET_NULL, null=True, blank=True
    )
    description = models.TextField(blank=True, null=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    is_recruiter = models.BooleanField(default=False, null=True, blank=True)

    location_policy = models.ForeignKey(
        LocationPolicy, on_delete=models.SET_NULL, null=True, blank=True
    )
    work_contract = models.ForeignKey(
        WorkContract, on_delete=models.SET_NULL, null=True, blank=True
    )

    min_pay = models.IntegerField(null=True, blank=True)
    max_pay = models.IntegerField(null=True, blank=True)
    pay_rate = models.ForeignKey(
        PayRate, on_delete=models.SET_NULL, null=True, blank=True
    )
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True
    )

    city = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True
    )

    note = models.TextField(null=True, blank=True)
    status = models.CharField(
        max_length=2, choices=StatusChoices.choices(), default=StatusChoices.default()
    )

    applied = models.BooleanField(null=True, blank=True)
    date_applied = models.DateField(null=True, blank=True)

    interviewed = models.BooleanField(null=True, blank=True)
    date_interviewed_set = models.DateField(null=True, blank=True)

    offered = models.BooleanField(null=True, blank=True)
    date_offered_set = models.DateField(null=True, blank=True)

    archived = models.BooleanField(null=True, blank=True, default=False)
    has_been_archived = models.BooleanField(
        null=True, blank=True, default=False)

    def __str__(self):
        return f"{self.company} - {self.job_title}"

    def _update_if_changed(self):
        if self.pk:
            logger.debug("PK exists")
            original = Job.objects.filter(pk=self.pk).first()
            if not original:
                logger.debug("Original does not exist")
                self.updated = timezone.now()
            else:
                logger.debug("Original exists")
                if original.status != self.status or original.note != self.note:
                    logger.debug("Status or note has changed")
                    logger.info("Updating job...")
                    self.updated = timezone.now()

    def _set_applied(self):
        logger.info("Setting applied...")

        try:
            if self.status in StatusChoices.get_applied_statuses():
                logger.info("Job is applied")

                if not self.applied:
                    self.applied = True

                if not self.date_applied:
                    self.date_applied = timezone.now()

            else:
                if self.status == StatusChoices.OPEN[0]:
                    logger.info("Job is not applied")

                    if self.applied:
                        self.applied = False

                    if self.date_applied:
                        self.date_applied = None

        except Job.DoesNotExist:
            pass

    def _set_interviewed(self):
        logger.info("Setting interviewed...")
        if self.status in [StatusChoices.INTERVIEW, StatusChoices.OFFER]:
            self.interviewed = True
            if not self.date_interviewed_set:
                self.date_interviewed_set = timezone.now()

    def save(self, *args, **kwargs):
        self._update_if_changed()
        self._set_applied()
        self._set_interviewed()
        super().save(*args, **kwargs)


class Settings(models.Model):
    """This model represents the job settings for a user."""

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name="job_settings"
    )

    auto_archive = models.BooleanField(null=True, blank=True, default=True)
    archive_after_weeks = models.IntegerField(null=True, blank=True, default=2)

accounts/views/delete.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from accounts.messages import AccountsMessageManager


@login_required
def delete_account_view(request):
    """Delete a user account

    This view is used to delete a user account. If the request
    method is POST, it deletes the user and their associated
    profile.

    If the request method is GET, it renders a confirmation page
    asking the user whether they want to delete their account.

    Args:
        - request: The HTTP request object

    Returns:
        - A redirect to the home page if the request method is POST
        - A confirmation page if the request method is GET
    """

    if request.method == "POST":
        user = request.user
        user.profile.delete()
        user.delete()
        messages.success(request, AccountsMessageManager.account_deleted_success)
        return redirect("core:home")

    # Render the confirmation page
    return render(request, "accounts/delete_account.html")

apptrack/jobs/views/job_add.py
"""Manages the adding of jobs for the requesting user."""
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from jobs.models import Board
from jobs.forms import JobForm

logger = logging.getLogger(__name__)


@login_required
@require_POST
def job_add_view(request):
    """Handles POST requests to add a new job for the requesting user.

    This view processes the submitted job form data. If the form is valid,
    it saves the job, associates it with the user's profile and board, and
    redirects to the referring URL. The referring URL is obtained from the
    request.POST dictionary, passed as a hidden input field on the add_job_modal.

    Args:
        request (HttpRequest): The request object containing form data.

    Returns:
        HttpResponseRedirect: Redirects to the referring URL. If the form is valid, the 
            response will contain a success message. If the form is invalid, the 
                response will contain an error message.
    """
    board = Board.objects.filter(profile=request.user.profile).first()
    referer_url = request.POST.get("referrer")

    if request.method == "POST":
        form = JobForm(request.POST)

        if form.is_valid():
            job = form.save()
            job.board = board
            job.profile = request.user.profile
            job.save()
            messages.success(request, "Job added successfully!")
        else:
            messages.error(request, f"Failed to add job {form.errors}. \
                           Please try again.")

    return redirect(referer_url)

apptrack/jobs/views/job_archive.py
"""Manages requests to archive jobs."""
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import View

from jobs.models import Job

logger = logging.getLogger(__name__)


class JobArchiveView(LoginRequiredMixin, View):
    """POST only view to archive jobs."""

    def post(self, request, *args, **kwargs):
        """Archives a job.

        This view takes a POST request to archive a job. The job_id is
        expected to be in the request.POST dictionary. The job is set to
        archived = True, and the view redirects to the jobs:board URL.

        Args:
            request (HttpRequest): The request object.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.

        Returns:
            HttpResponseRedirect: The response object.
        """
        logger.debug("Archiving job...")
        job_id = request.POST.get("job_id")
        job = Job.objects.get(id=job_id)

        job.archived = True  # Assuming `is_archived` is a boolean field
        job.save()
        logger.debug("Job %s archived", job_id)
        return redirect("jobs:board")

apptrack/jobs/views/job_assign.py
"""Manages the assignment of jobs to columns. In the job board view."""
import logging

from django.contrib.auth import get_user_model

from rest_framework.response import Response
from rest_framework.views import APIView

from jobs.models import Column, Job

logger = logging.getLogger(__name__)

User = get_user_model()


class JobAssignView(APIView):
    """Manages the assignment of jobs to columns.

    This class view manages the assignment of jobs to columns in the job board view.
    It handles POST requests. APIView is used to provide a Response object.
    """

    def post(self, request, *args, **kwargs):
        """Handles POST requests for the assignment of a job to a column.

        This function manages the assignment of a job to a column in the job board view.
        It handles POST requests and assigns the job to the column specified by the
        url parameter 'col_id' and the job specified by the url parameter 'job_id'.

        Args:
            request (HttpRequest): The request object.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.
                'col_id' (int): The ID of the column to assign the job to.
                'job_id' (int): The ID of the job to assign to the column.

        Returns:
            Response: The response object.
        """
        logger.debug("Assigning job...")
        col_id = kwargs["col_id"]
        job_id = kwargs["job_id"]

        column = Column.objects.get(id=col_id)
        job = Job.objects.get(id=job_id)

        job.column = column
        logger.debug("Job assigned to column %s", column)

        job.save()
        column.save()
        logger.debug("Job saved successfully to column: %s", column)

        data = {"job_status": job.status, "job_id": job.id}
        return Response(data)

apptrack/jobs/views/job_delete.py
"""Manages the job delete view for the requesting user."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import View

from jobs.models import Job


class JobDeleteView(LoginRequiredMixin, SuccessMessageMixin, View):
    """Manages the job delete view for the requesting user.

    If the request method is POST, it deletes the job and redirects to the job board.
    If the request method is GET, it redirects to the core home page.
    """
    model = Job
    success_url = reverse_lazy("jobs:board")
    success_message = "Job deleted successfully"

    def get(self, request, *args, **kwargs):  # noqa: D102
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):  # noqa: D102
        job = self.model.objects.get(id=kwargs["pk"])
        job.delete()
        return redirect(reverse("core:home"))

apptrack/jobs/views/job_download.py
"""This module processes the job download view.

Manages the job download view for the requesting user. Allowing them to download a CSV 
file of their jobs based on a provided date range.
"""

import csv

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from jobs.forms import DownloadJobsForm
from jobs.models import Job


@login_required
def job_download_view(request):
    """Manages the job download view for the requesting user.

    Allows the user to download a CSV file of their jobs based on a provided date range.
    If the request method is GET, it renders a form for the user to input the date 
    range. If the request method is POST, it generates a CSV file with the jobs in the 
    specified date range and returns it as a response.

    The CSV file will have the following columns: ID, Job Title, Company, URL, Status,
    and Updated.

    Args:
        request: The current request

    Returns:
        HttpResponse: A CSV file with the jobs in the specified date range if the 
            request method is POST, or a form for the user to input the date range if 
                the request method is GET
    """
    if request.method == "GET":
        form = DownloadJobsForm()
        return render(
            request,
            "jobs/download_jobs.html",
            {"form": form, "user_id": request.user.id},
        )

    # Handle POST request (CSV file generation)
    start_date = request.POST.get("start_date")
    end_date = request.POST.get("end_date")

    # Filter jobs based on the `updated` field
    jobs = Job.objects.filter(updated__range=(
        start_date, end_date)).order_by("id")

    filename = f"jobs_{start_date}_{end_date}.csv"
    # Prepare the response
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )

    # Write the CSV file
    writer = csv.writer(response)
    writer.writerow(
        ["ID", "Job Title", "Company", "URL", "Status", "Updated"]
    )  # CSV headers

    for job in jobs:
        writer.writerow(
            [
                job.id,
                job.job_title,
                job.company,
                job.url,
                job.get_status_display(),
                job.updated,
            ]
        )

    return response

apptrack/jobs/views/job_edit.py
"""Job edit view.

Manages the job edit view for the requesting user.
"""
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls.exceptions import NoReverseMatch
from django.views.decorators.http import require_POST

from jobs.models import Job
from jobs.forms import JobForm

logger = logging.getLogger(__name__)


@login_required
@require_POST
def job_edit_view(request, pk):
    """Manages POST requests for the job edit view. GET requests are not supported.

    This view handles the editing of a job for the requesting user. If the request
    method is POST, it validates the form and saves the changes.

    Args:
        request (HttpRequest): The request object.
        pk (int): The primary key of the job to edit.

    Returns:
        HttpResponseRedirect: The response object.
    """
    logger.info("Editing job...")
    job = Job.objects.get(pk=pk)
    referer_url = request.POST.get("editJobReferrer")
    logger.info("Referer URL: %s", referer_url)
    if request.method == "POST":
        logger.info("Request method is POST")
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            logger.info("Form is valid")
            job = form.save()
            job.save()
            logger.info("Job saved")
            logger.info("New job url: %s", job.url)
            try:
                return redirect(referer_url)
            except (NoReverseMatch, TypeError):
                return redirect("jobs:board")

apptrack/jobs/views/task_edit.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from jobs.models import InterviewTask


@login_required
@require_POST
def task_edit_view(request, id):
    if request.method == "POST":
        task = InterviewTask.objects.get(id=id)
        is_completed = json.loads(request.body)['completed']
        if is_completed == "true":
            task.is_completed = True
        else:
            task.is_completed = False
        task.save()
        return HttpResponse(status=200)

jobs/templates/jobs/modals/add.html
<!DOCTYPE html>

<div class="modal fade" id="addJobModal" tabindex="-1" aria-labelledby="addJobModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addJobModalLabel">Add Job</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" id="addJobForm" action="{% url 'jobs:add' %}">
                    {% load crispy_forms_tags %}
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <h5>Company</h5>
                        </div>
                        <div class="col">
                            <h5>Job</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <label for="id_company_name">Company</label>
                                    <input type="text" name="company_name" id="id_company_name" class="form-control" list="company-list" value="{{ job_form.company_name.value|default:'' }}" />
                                    <datalist id="company-list">
                                        {% for company in request.user.profile.company_set.all %}
                                            <option value="{{ company.name }}">
                                        {% endfor %}
                                    </datalist>
                                    {% if job_form.company_name.errors %}
                                        <div class="invalid-feedback">
                                            {{ job_form.company_name.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.is_recruiter|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col">
                                    {{ job_form.city|as_crispy_field }}
                                </div>
                                <div class="col">
                                    {{ job_form.region|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.country|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col-8">
                                    {{ job_form.job_title|as_crispy_field }}
                                </div>
                                <div class="col-4">
                                    {{ job_form.job_function|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.description|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <h5>Pay</h5>
                        </div>
                        <div class="col">
                            <h5>Contract</h5>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    {{ job_form.min_pay|as_crispy_field }}
                                </div>
                                <div class="col">
                                    {{ job_form.max_pay|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.pay_rate|as_crispy_field }}
                                </div>
                                <div class="col">
                                    {{ job_form.currency|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    {{ job_form.work_contract|as_crispy_field }}
                                </div>
                                <div class="col">
                                    {{ job_form.location_policy|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <h5>Application Info</h5>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {{ job_form.note|as_crispy_field }}
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    {{ job_form.status|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.url|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ job_form.source|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="referrer" id="referrerInput">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

jobs/templates/jobs/modals/detail.html
<!DOCTYPE html>
{% load static %}
{% for job in jobs %}
    {% if job.id %}
    <div class="modal fade" id="jobDetailModal{{ job.id }}" tabindex="-1" aria-labelledby="jobDetailModalLabel{{ job.id }}" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <h5>Company</h5>
                        </div>
                        <div class="col">
                            <h5>Job</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <strong>Company:</strong> {{ job.company }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>Recruiter:</strong> {{ job.is_recruiter }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col">
                                    <strong>City:</strong> {{ job.city }}
                                </div>
                                <div class="col">
                                    <strong>Region:</strong> {{ job.region }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>Country:</strong> {{ job.get_country_display }}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col-8">
                                    <strong>Job Title:</strong> {{ job.job_title }}
                                </div>
                                <div class="col-4">
                                    <strong>Job Function:</strong> {{ job.get_job_function_display }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>Description:</strong> {{ job.description }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <h5>Pay</h5>
                        </div>
                        <div class="col">
                            <h5>Contract</h5>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <strong>Min Pay:</strong> {{ job.min_pay }}
                                </div>
                                <div class="col">
                                    <strong>Max Pay:</strong> {{ job.max_pay }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>Pay Rate:</strong> {{ job.pay_rate }}
                                </div>
                                <div class="col">
                                    <strong>Currency:</strong> {{ job.currency }}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <strong>Work Contract:</strong> {{ job.work_contract }}
                                </div>
                                <div class="col">
                                    <strong>Location Policy:</strong> {{ job.location_policy }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <h5>Application Info</h5>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <strong>Note:</strong> {{ job.note }}
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <strong>Status:</strong> {{ job.get_status_display }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>URL:</strong> {{ job.url }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <strong>Source:</strong> {{ job.get_source_display }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editJobModal{{ job.id }}" id="editJobButton">Edit</a>
                    <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#jobDeleteConfirm{{ job.id }}">Delete</a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                    {% if job.url and job.url != '' %}
                        <a href="{{ job.url }}" target="_blank" class="btn btn-primary">Apply</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}

{% endfor %}