accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "accounts"
urlpatterns = [
    path("api/<int:id>/", views.ProfileAPI.as_view(), name="api"),
    path("registration/", views.registration_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/<int:id>/", views.ProfileView.as_view(), name="profile"),
    path("settings/<int:id>/", views.settings_view, name="settings"),
    path("password-reset/", views.password_reset_view, name="password_reset"),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "verify-email/<int:user_id>/<str:token>/",
        views.verify_email_view,
        name="verify_email",
    ),
    path("resend/", views.resend_view, name="resend"),
    path("delete-account/", views.delete_account_view, name="delete_account"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("post/<int:id>/", views.post, name="post"),

]

jobs/urls.py
# noqa: D100
from django.urls import path
from . import views
app_name = "jobs"

urlpatterns = [
    path("add/", views.job_add_view, name="add"),
    path("archive/", views.JobArchiveView.as_view(), name="archive"),
    path("delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete"),
    path("download/", views.job_download_view, name="download"),
    path("edit/<int:pk>/", views.job_edit_view, name="edit"),
    path("list/", views.JobListView.as_view(), name="list"),
    path("settings/", views.settings_view, name="settings"),
]

accounts/models.py
import logging

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager
# Create your models here.

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """Custom User model that uses email instead of username."""

    email = models.EmailField(_("email address"), unique=True)
    email_verified = models.BooleanField(default=False)

    last_verification_email_sent = models.DateTimeField(null=True, blank=True)
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"  # Use email instead of username for authentication
    # These fields will be prompted in createsuperuser
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return self.email


class Profile(models.Model):
    """Profile model for CustomUser."""

    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="profile", unique=True
    )
    email_comms_opt_in = models.BooleanField(default=False)
    birth_date = models.DateField(null=True, blank=True)
    current_applications_made = models.IntegerField(
        null=True, blank=True, default=0)
    last_reset = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

jobs/models.py
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils import timezone

from accounts.models import Profile
from core.models import (
    Country,
    Currency,
    JobFunction,
    LocationPolicy,
    WorkContract,
    PayRate,
)

from core.choices import StatusChoices, SourceChoices

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create your models here.


class Job(models.Model):
    id = models.BigAutoField(primary_key=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    url = models.URLField(blank=True, null=True)
    source = models.CharField(
        max_length=2, choices=SourceChoices.choices(), null=True, blank=True
    )

    job_title = models.CharField(max_length=100, blank=True, null=True)
    job_function = models.ForeignKey(
        JobFunction, on_delete=models.SET_NULL, null=True, blank=True
    )
    description = models.TextField(blank=True, null=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    is_recruiter = models.BooleanField(default=False, null=True, blank=True)

    location_policy = models.ForeignKey(
        LocationPolicy, on_delete=models.SET_NULL, null=True, blank=True
    )
    work_contract = models.ForeignKey(
        WorkContract, on_delete=models.SET_NULL, null=True, blank=True
    )

    min_pay = models.IntegerField(null=True, blank=True)
    max_pay = models.IntegerField(null=True, blank=True)
    pay_rate = models.ForeignKey(
        PayRate, on_delete=models.SET_NULL, null=True, blank=True
    )
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True
    )

    city = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True
    )

    note = models.TextField(null=True, blank=True)
    status = models.CharField(
        max_length=2, choices=StatusChoices.choices(), default=StatusChoices.default()
    )

    applied = models.BooleanField(null=True, blank=True)
    date_applied = models.DateField(null=True, blank=True)

    interviewed = models.BooleanField(null=True, blank=True)
    date_interviewed_set = models.DateField(null=True, blank=True)

    offered = models.BooleanField(null=True, blank=True)
    date_offered_set = models.DateField(null=True, blank=True)

    archived = models.BooleanField(null=True, blank=True, default=False)
    has_been_archived = models.BooleanField(
        null=True, blank=True, default=False)

    def __str__(self):
        return f"{self.company} - {self.job_title}"

    def _update_if_changed(self):
        if self.pk:
            logger.debug("PK exists")
            original = Job.objects.filter(pk=self.pk).first()
            if not original:
                logger.debug("Original does not exist")
                self.updated = timezone.now()
            else:
                logger.debug("Original exists")
                if original.status != self.status or original.note != self.note:
                    logger.debug("Status or note has changed")
                    logger.info("Updating job...")
                    self.updated = timezone.now()

    def _set_applied(self):
        logger.info("Setting applied...")

        try:
            if self.status in StatusChoices.get_applied_statuses():
                logger.info("Job is applied")

                if not self.applied:
                    self.applied = True

                if not self.date_applied:
                    self.date_applied = timezone.now()

            else:
                if self.status == StatusChoices.OPEN[0]:
                    logger.info("Job is not applied")

                    if self.applied:
                        self.applied = False

                    if self.date_applied:
                        self.date_applied = None

        except Job.DoesNotExist:
            pass

    def _set_interviewed(self):
        logger.info("Setting interviewed...")
        if self.status in [StatusChoices.INTERVIEW, StatusChoices.OFFER]:
            self.interviewed = True
            if not self.date_interviewed_set:
                self.date_interviewed_set = timezone.now()

    def save(self, *args, **kwargs):
        self._update_if_changed()
        self._set_applied()
        self._set_interviewed()
        super().save(*args, **kwargs)


class Settings(models.Model):
    """This model represents the job settings for a user."""

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name="job_settings"
    )

    auto_archive = models.BooleanField(null=True, blank=True, default=True)
    archive_after_weeks = models.IntegerField(null=True, blank=True, default=2)

accounts/views/api.py
from django.contrib.auth import get_user_model
from rest_framework.response import Response
from rest_framework.views import APIView

from jobs.models import Job

from accounts.models import Profile
from .utils import ConversionCalculator

User = get_user_model()


class ProfileAPI(APIView):
    def get(self, request, id):
        """Handles GET requests to the API for a given user.

        This function gets the data for a given user and
        returns it as a JSON response.

        Args:
            - :param request: The HTTP request object
            - :param id: The id of the user whose data is being requested

        Returns:
            - :return: A Response object containing the JSON data
        """
        print("Request recieved for user: " + str(id))
        user = User(id=id)
        print("User found: " + user.email)
        profile = Profile.objects.get(user=user)
        print("Profile found: " + str(profile.id))
        data = {
            "basic_stats": self._get_basic_stats(profile),
        }
        print("Data: " + str(data))
        return Response(data)

    def _get_basic_stats(self, profile):
        """Retrieves basic statistics related to job applications for a given user profile.

        This method calculates various statistics such as the total number of jobs,
        active jobs, applied jobs, interviewed jobs, and offers associated with the
        user's profile. Additionally, it computes conversion rates and scores using
        these statistics.

        Args:
            - profile (`Profile`): The Profile object representing the user's profile.

        Returns:
            - `dict`: A dictionary containing the following keys and their respective values:
                - `total_jobs`: Total number of jobs associated with the profile.
                - `total_active_jobs`: Total number of active (non-archived) jobs.
                - `total_applied_jobs`: Total number of jobs the user has applied to.
                - `total_interviewed_jobs`: Total number of jobs for which the user has been interviewed.
                - `total_offers`: Total number of job offers received.
                - `total_active_interviews`: Total number of active interviews.
                - `total_active_offers`: Total number of active offers.
                - `conversion_score`: Conversion score calculated based on applications, interviews, and offers.
                - `conversion_rate`: Conversion rate from applications to offers.
                - `interview_conversion_rate`: Conversion rate from applications to interviews.
                - `offer_conversion_rate`: Conversion rate from applications to offers.
        """
        total_jobs = Job.objects.filter(profile=profile).count()
        total_active_jobs = Job.objects.filter(
            profile=profile, archived=False).count()
        total_applied_jobs = Job.objects.filter(
            profile=profile, applied=True).count()
        total_interviewed_jobs = Job.objects.filter(
            profile=profile, interviewed=True
        ).count()
        total_active_interviews = Job.objects.filter(
            profile=profile, interviewed=True, archived=False
        ).count()
        total_active_offers = Job.objects.filter(
            profile=profile, offered=True, archived=False
        ).count()
        total_offers = Job.objects.filter(profile=profile).count()

        return {
            "total_jobs": total_jobs,
            "total_applied_jobs": total_applied_jobs,
            "total_interviewed_jobs": total_interviewed_jobs,
            "total_offers": total_offers,
            "total_active_jobs": total_active_jobs,
            "total_active_interviews": total_active_interviews,
            "total_active_offers": total_active_offers,
            "conversion_score": ConversionCalculator.calculate_conversion_score(
                total_applied_jobs, total_interviewed_jobs, total_offers
            ),
            "conversion_rate": ConversionCalculator.calculate_conversion_rate(
                total_applied_jobs, total_interviewed_jobs, total_offers
            ),
            "interview_conversion_rate": ConversionCalculator.calculate_basic_conversion_rate(
                total_applied_jobs, total_interviewed_jobs
            ),
            "offer_conversion_rate": ConversionCalculator.calculate_basic_conversion_rate(
                total_applied_jobs, total_offers
            ),
        }


"""
class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        labels = [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July'
        ]
        chartLabel = "my data"
        chartdata = [0, 10, 5, 2, 20, 30, 45]
        data = {
            "labels": labels,
            "chartLabel": chartLabel,
            "chartdata": chartdata,
        }
        return Response(data)
"""

accounts/views/dashboard.py
from django.shortcuts import render
from django.utils import timezone

from jobs.models import Job


def dashboard_view(request):
    """A view that renders a dashboard for the user.

    This view renders the dashboard template with the following data:

    - The 10 most recently updated jobs
    - The 10 most recently scheduled interviews
    - The 10 tasks with the highest priority

    All data is associated with the user making
    the request.

    Args:
        - request: The current request

    Returns:
        - The rendered dashboard template
    """
    jobs = (
        Job.objects.filter(profile=request.user.profile, archived=False)
        .order_by("updated")
        .all()[:5]
    )

    context = {
        "user_id": request.user.id,
        "jobs": jobs
    }
    return render(request, "accounts/dashboard.html", context)

accounts/views/delete.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from accounts.messages import AccountsMessageManager


@login_required
def delete_account_view(request):
    """Delete a user account

    This view is used to delete a user account. If the request
    method is POST, it deletes the user and their associated
    profile.

    If the request method is GET, it renders a confirmation page
    asking the user whether they want to delete their account.

    Args:
        - request: The HTTP request object

    Returns:
        - A redirect to the home page if the request method is POST
        - A confirmation page if the request method is GET
    """

    if request.method == "POST":
        user = request.user
        user.profile.delete()
        user.delete()
        messages.success(request, AccountsMessageManager.account_deleted_success)
        return redirect("core:home")

    # Render the confirmation page
    return render(request, "accounts/delete_account.html")

accounts/views/logout.py
import logging

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


@login_required
def logout_view(request):
    """
    Log out the user and redirect to the home page.

    This view logs out the currently authenticated user and
    redirects them to the home page. It requires the user to
    be logged in before accessing it.

    Args:
        request: The HTTP request object.

    Returns:
        A redirect to the home page.
    """

    logout(request)
    return redirect("core:home")

accounts/views/verify_email.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, redirect

from accounts.messages import AccountsMessageManager


def verify_email_view(request, user_id, token):
    """
    View that verifies a user's email address.

    Args:
        - request (`django.http.HttpRequest`): The request object.
        - user_id (`int`): The ID of the user to verify.
        - token (`str`): The verification token.

    Returns:
        - A redirect to the login page if the token is valid,
        or a 404 if the user or token is invalid.

    """
    from accounts.tokens import email_verification_token  # Import the token generator

    UserModel = get_user_model()
    user = get_object_or_404(UserModel, id=user_id)

    if email_verification_token.check_token(user, token):
        user.email_verified = True
        user.save()
        messages.success(request, AccountsMessageManager.email_verified)
        return redirect("accounts:login")

accounts/templates/accounts/dashboard.html
<!DOCTYPE html>

{% extends 'core/base_authenticated.html' %}

{% load static %}
<head>
    {% block title %}
    <title>Dashboard</title>
    {% endblock title %}
</head>

{% block content %}
<div class="row">
    <div class="col">
        <h1>Dashboard</h1>
    </div>
</div>

<div class="row py-3">
    <div class="col">
        <div class="card">
            <div class="card-header text-center">
                <h5>Jobs</h5>
            </div>
            <div class="card-body">
                <div class="list-group">
                    {% for job in jobs %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col">
                                <strong>{{ job.job_title }}</strong>
                            </div>
                            <div class="col">
                                <strong>{{ job.get_status_display }}</strong>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col">
                                <strong>No Jobs</strong>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="card-footer">
                <div class="row text-center">
                    <div class="col">
                        <a class="btn btn-sm btn-primary" href="{% url 'jobs:list' %}">Jobs List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="row">
    <div class="col">
        <h2>Basic Stats</h2>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Statistic
            </th>
            <th>
                Value
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                Total Applications
            </td>
            <td>
                <strong id="totalApplications"></strong>
            </td>
        </tr>
    </tbody>
</table>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script> 

<script src="{% static 'accounts/scripts/basicStats.js' %}"></script>

<!--
<script src="{% static 'accounts/scripts/jobFunctionConversion.js' %}"></script>
<script src="{% static 'accounts/scripts/jobSourceConversion.js' %}"></script>
-->


{% endblock %}

accounts/templates/accounts/delete_account.html
{% extends "core/base_unauthenticated.html" %}

{% block content %}
  <div class="container">
    <h2>Are you sure you want to delete your account?</h2>
    <p>This action is irreversible, and all your data will be lost.</p>

    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Yes, delete my account</button>
      <a href="{% url 'accounts:profile' user.profile.id %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>

{% extends "core/base_unauthenticated.html" %}

{% block content %}

    <div class="card w-50 m-auto">
        <div class="card-header">
            <h2 class="card-title">Login</h2>
        </div>
  
        <div class="card-body">
            {% load crispy_forms_tags %}
            <form method="POST">
                {% csrf_token %}
                {{ form.honeypot }}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <div class="card-footer text-center">
            <a href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
            <a href="{% url 'accounts:register' %}">Register</a>
        </div>

    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'core/base_unauthenticated.html' %}

{% block content %}
<h2>You have been logged out</h2>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "core/base_unauthenticated.html" %}
{% block content %}
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                        <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_email">Email</label>
                                    <input type="email" name="email"  class="form-control"
                                            autocomplete="email" maxlength="254" required id="id_email"
                                            placeholder="Enter email">
                                </div>
                            </div>
                        </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group mt-0 mb-1">
                                    <button type="submit" class="col-md-12 btn btn-dark">Submit
                                    </button>
                                </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'accounts:register' %}">Create A New Account</a><br><br>
                            <a href="{% url 'accounts:login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "core/base_unauthenticated.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

accounts/templates/accounts/profile.html
<!DOCTYPE html>

{% extends "core/base_authenticated.html" %}
<head>
    {% block title %}
    <title>Profile</title>
    {% endblock title %}
</head>

{% block content %}

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Profile</h2>
        </div>
  
        <div class="card-body">
            <h5 class="card-title">{{ user.username }}</h5>
            <p class="card-text">Email: {{ user.email }}</p>
            <p class="card-text">First Name: {{ user.first_name }}</p>
            <p class="card-text">Last Name: {{ user.last_name }}</p>
            <p class="card-text">Date Joined: {{ user.date_joined }}</p>
        </div>

        <div class="card-footer text-center">
            <a class="btn btn-primary" href="{% url 'accounts:settings' user.profile.id %}">Settings</a>
        </div>

    </div>
{% endblock %}

accounts/templates/accounts/profile_settings.html
<!DOCTYPE html>
{% extends 'core/base_authenticated.html' %}

{% load crispy_forms_tags %}
<head>{% block subtitle %}<title>Profile | Settings</title>{% endblock %}</head>
{% block content %}

  <div class="card w-50 m-auto">
      <div class="card-header">
        <h2>Profile Page</h2>
      </div>

      <div class="card-body">
        {% load crispy_forms_tags %}
        <form method="POST">
            {% csrf_token %}

            <div class="row">
                <div class="col m-auto">
                    {{ user_form.honeypot }}
                    {{ user_form.first_name|as_crispy_field }}
                </div>
                <div class="col m-auto">
                    {{ user_form.last_name|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col m-auto">
                    {{ profile_form.birth_date|as_crispy_field }}
                </div>
                <div class="col m-auto">
                    {{ user_form.email|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col m-auto">
                    <p><strong>Would you like to opt in for communication emails from Apptrack?</strong></p>
                </div>
                <div class="col m-auto">
                    {{ profile_form.email_comms_opt_in|as_crispy_field }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
    <div class="card-footer text-center">
        <a class="btn btn-danger" href="{% url 'accounts:delete_account' %}">Delete Account</a>
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
{% extends 'core/base_unauthenticated.html' %}

{% block content %} 
    <div class="card w-50 m-auto">
        <div class="card-header">
            <h2 class="card-title">Register</h2>
        </div>
  
        <div class="card-body">
            {% load crispy_forms_tags %}
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col m-auto">
                        {{ user_form.honeypot }}
                        {{ user_form.email|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        {{ user_form.password1|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        {{ user_form.password2|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        {{ user_form.first_name|as_crispy_field }}
                    </div>
                    <div class="col m-auto">
                        {{ user_form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        {{ profile_form.birth_date|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        <p><strong>Would you like to opt in for communication emails from Apptrack?</strong></p>
                    </div>
                    <div class="col m-auto">
                        {{ profile_form.email_comms_opt_in|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col m-auto">
                        {{ user_form.captcha }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
        <div class="card-footer text-center">
            <a href="{% url 'accounts:login' %}">Login</a>
        </div>

    </div>
{% endblock %}

accounts/templates/accounts/resend.html
{% extends "core/base_unauthenticated.html" %}

{% load crispy_forms_tags %}

{% block content %}
    
    <div class="card m-auto w-50">
        <div class="card-header justify-content-center">
            <h2>Resend Verification Email</h2>
        </div>

        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.honeypot }}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Resend Email</button>
            </form>
        </div>
    </div>

{% endblock %}