accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "accounts"
urlpatterns = [
    path("api/<int:id>/", views.ProfileAPI.as_view(), name="api"),
    path("registration/", views.registration_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/<int:id>/", views.ProfileView.as_view(), name="profile"),
    path("settings/<int:id>/", views.settings_view, name="settings"),
    path("password-reset/", views.password_reset_view, name="password_reset"),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "verify-email/<int:user_id>/<str:token>/",
        views.verify_email_view,
        name="verify_email",
    ),
    path("resend/", views.resend_view, name="resend"),
    path("delete-account/", views.delete_account_view, name="delete_account"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("post/<int:id>/", views.post, name="post"),

]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("contact/", views.contact_view, name="contact"),
    path("privacy-policy/", views.privacy_policy_view, name="privacy_policy")
]

jobs/urls.py
# noqa: D100
from django.urls import path
from . import views
app_name = "jobs"

urlpatterns = [
    path("add/", views.job_add_view, name="add"),
    path("archive/", views.JobArchiveView.as_view(), name="archive"),
    path("delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete"),
    path("download/", views.job_download_view, name="download"),
    path("edit/<int:pk>/", views.job_edit_view, name="edit"),
    path("list/", views.JobListView.as_view(), name="list"),
    path("settings/", views.settings_view, name="settings"),
]

core/models.py
from django.db import models


class Currency(models.Model):
    alpha_3 = models.CharField(max_length=3)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Country(models.Model):
    alpha_2 = models.CharField(max_length=2)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class JobFunction(models.Model):
    code = models.CharField(max_length=4)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class LocationPolicy(models.Model):
    code = models.CharField(max_length=2)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PayRate(models.Model):
    code = models.CharField(max_length=2)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class WorkContract(models.Model):
    code = models.CharField(max_length=2)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.core.validators import EmailValidator


class ContactForm(forms.Form):
    honeypot = forms.CharField(required=False, widget=forms.HiddenInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.CharField(validators=[EmailValidator()], required=True)
    phone = forms.CharField(max_length=25)
    message = forms.CharField(widget=forms.Textarea)

core/views.py
import logging

from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from .forms import ContactForm

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

User = get_user_model()


def home_view(request):
    return render(request, "core/index.html")


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["honeypot"]:
                logger.debug("Honeypot field filled")
                # Honeypot field should be empty. If it's filled, treat it as spam.
                messages.error(request, "Spam detected")
                # Redirect to prevent bot resubmission
                return redirect("core:home")

            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            phone = form.cleaned_data["phone"]

            html_message = f"""
            <p><strong>First Name:</strong> {first_name}</p>
            <p><strong>Last Name:</strong> {last_name}</p>
            <p><strong>Email:</strong> {email}</p>
            <p><strong>Phone:</strong> {phone}</p>
            <p><strong>Message:</strong></p>
            <br>
            <p>{message}</p>
            """

            # Compose email subject and message
            subject = f"Contact Form Submission from {first_name} {last_name}"

            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,  # From email
                ["charlie.marshall1996@gmail.com"],  # To email
                fail_silently=False,
                html_message=html_message,
            )

            messages.success(request, "Your message has been sent successfully!")
            return redirect("core:home")
        else:
            logger.debug("Invalid form data")
            logger.debug("Errors: %s", form.errors)
            messages.error(request, "Please fill out the form correctly.")
            return redirect("core:contact")
    else:
        form = ContactForm()
        return render(request, "core/contact.html", {"form": form})


def privacy_policy_view(request):
    return render(request, "core/privacy_policy.html")

core/templates/core/base_authenticated.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %} {% endblock %}
  <link rel="icon" type="image/x-icon" href="{% static 'core/favicon/favicon.ico' %}">
  
  {% csrf_token %}
  <meta name="csrf-token" content="{{ csrf_token }}">
  

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  
  <!-- Bootstrap CSS -->
   
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
  
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'core/styles/reset.css' %}">
  <link rel="stylesheet" href="{% static 'core/styles/style.css' %}">

  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <!-- UserID -->
  <script>
    const userID = "{{ user_id }}";
    var userDataEndpoint = "{% url 'accounts:api' 0 %}".replace("0", userID);
  </script>
  
  {% block css %}
  {% endblock %}
</head>

<body class="d-flex flex-column min-vh-100 container-fluid px-0">
  <!-- Header -->

  <header>
    <nav class="navbar navbar navbar-expand-md navbar-light px-3">
      <a class="navbar-brand display-5" href="{% url 'accounts:dashboard' %}"><img class="img nav-icon" src="{% static 'core/nav-icon.svg' %}" alt=""></a>

      <!-- Toggler/collapsible Button -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav w-100">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/accounts/dashboard/' %}active{% endif %}" href="{% url 'accounts:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if '/jobs/' in request.path %}active{% endif %}" href="{% url 'jobs:list' %}">Jobs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/accounts/profile/{{ user.profile.id }}' %}active{% endif %}" href="{% url 'accounts:profile' user.profile.id %}">Profile</a>
          </li>
          <li class="navbar-item ms-auto">
            <a class="nav-link {% if request.path == '/accounts/logout/' %}active{% endif %}" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
        
  </header>

  <!-- Content -->
  {% include 'core/messages.html' %}
  <div class="container" id="content">
    {% block content %}
    {% endblock %}
    {% block scripts %}
    
    {% endblock %}
  </div>

  <footer class="footer mt-auto px-0">
    <nav class="navbar navbar-expand-lg bg-body-tertiary px-3" id="footer">
      <ul class="navbar-nav">
        <li class="nav-item">
          <p class="nav-link">&copy; AppTrack 2024, All Rights Reserved</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:privacy_policy' %}">Privacy Policy</a>
        </li>
      </ul>
    </nav>
  </footer>

</body>





</html>

core/templates/core/base_unauthenticated.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AppTrack</title>

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'core/favicon/favicon.ico' %}">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'core/styles/reset.css' %}">
  <link rel="stylesheet" href="{% static 'core/styles/style.css' %}">
</head>

<body class="d-flex flex-column min-vh-100 container-fluid px-0">
<!-- Header -->

  <header class="row">
    <div class="col-8 mx-auto">
      <nav class="navbar navbar navbar-expand-md navbar-light px-3">
        <a class="navbar-brand" href="{% url 'core:home' %}"><img class="img nav-icon" src="{% static 'core/nav-icon.svg' %}" alt=""></a>
  
        <!-- Toggler/collapsible Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav w-100">
            <li class="nav-item d-none d-md-flex">
              <a class="nav-link {% if request.path == 'core:contact' %}active{% endif %}" href="{% url 'core:contact' %}">Contact</a>
            </li>
            <li class="nav-item d-flex d-md-none ms-auto">
              <a class="nav-link {% if request.path == 'core:contact' %}active{% endif %}" href="{% url 'core:contact' %}">Contact</a>
            </li>
            <li class="nav-item d-none d-md-flex ms-auto px-1">
              <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item d-flex d-md-none ms-auto p-2">
              <a class="btn btn-sm btn-primary" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item d-none d-md-flex px-1">
              <a class="btn btn-outline-primary" href="{% url 'accounts:register' %}">Register</a>
            </li>
            
            <li class="nav-item d-flex d-md-none ms-auto p-2">
              <a class="btn btn-sm btn-outline-primary" href="{% url 'accounts:register' %}">Register</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <!-- Content -->
  <div class="container align-content-center">

    {% include 'core/messages.html' %}
  </div>

  <div class="container-fluid justify-self-center mt-auto" id="content">
    {% block content %}
    {% endblock %}
  </div>

  <footer class="footer mt-auto px-0">
    <nav class="navbar navbar-expand-lg bg-body-tertiary px-3" id="footer">
      <ul class="navbar-nav">
        <li class="nav-item">
          <p class="nav-link">&copy; AppTrack 2024, All Rights Reserved</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:privacy_policy' %}">Privacy Policy</a>
        </li>
      </ul>
    </nav>
  </footer>

</body>



{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

</html>

core/templates/core/contact.html
{% extends 'core/base_unauthenticated.html' %}

{% block content %}
<div class="card w-50 m-auto">
    <div class="card-header">
        <h2 class="card-title">Contact Us</h2>
    </div>

    {% load crispy_forms_tags %}
    <form method="POST">
        <div class="card-body">
            {% csrf_token %}
            {{ form.honeypot }}
            {{ form|crispy }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Send Message</button>
        </div>
    </form>

</div>

{% endblock %}

core/templates/core/index.html
<!DOCTYPE html>
{% extends 'core/base_unauthenticated.html' %}

{% load static %}

{% block content %}

<div class="row text-center vh-100 align-items-center">
    <div class="col-10 mx-auto">
        <div class="row text-center">
            <div class="col mx-auto py-2">
                <p class="hero-heading display-5">Stay on top.</p>
                <p class="hero-heading display-5">Streamline your search.</p>
                <p class="hero-heading display-5">Secure your opportunity.</p>
            </div>            
        </div>
        <div class="row text-center">
            <div class="col mx-auto py-2">
                <p class="mx-auto hero-description fs-6">Take control of your job search for <strong>free</strong> with AppTrack. Effortlessly organize and track every application in one place. Stay focused, stay prepared, and land your next opportunity.</p>
            </div>
        </div>
        <div class="row text-center">
            <div class="col mx-auto py-2">
                <a type="button" class="btn btn-hero btn-primary btn-lg px-4 gap-3" href="{% url 'accounts:register' %}">Sign Up</a>
            </div>
        </div>
    </div>
</div>

<hr>
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <h2 class="text-start display-5">About AppTrack</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p class="text-start mx-auto fs-4">
                    AppTrack is an intuitive web app designed to help job seekers efficiently manage and track their job applications. Whether you're applying to multiple positions or organizing follow-ups, Apptrack simplifies the process by allowing candidates to monitor their progress, set reminders, and store essential application details - all in one place.
                    With AppTrack, staying organized during your job search has never been easier. The platform is designed to save time, reduce stress, and increase your chances of landing the perfect job. From application submission to interview scheduling, keep track of every step on your career journey with ease.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p class="fs-5"><strong>Stay on top of your job search:</strong></p>
            </div>
        </div>
        <div class="row d-flex flex-row align-self-center py-2 px-0">
            <div class="col align-content-center">
                <a type="button" class="text-start btn btn-outline-primary btn-sm fs-5" href="{% url 'accounts:register' %}">Register with AppTrack today!</a>
            </div>
        </div>
    </div>
    <div class="col d-flex justify-self-end align-items-center d-none d-lg-flex">
        <img class="img-fluid mx-auto px-0" src="{% static 'core/man-in-suit.jpg' %}" alt="">
    </div>
</div>


{% endblock %}

core/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
        {% with message_class="alert-info" %}
            {% if message.tags == 'error' %}
                {% with message_class="alert-danger" %}
                {% endwith %}
            {% elif message.tags == 'success' %}
                {% with message_class="alert-success" %}
                {% endwith %}
            {% elif message.tags == 'warning' %}
                {% with message_class="alert-warning" %}
                {% endwith %}
            {% elif message.tags == 'info' %}
                {% with message_class="alert-info" %}
                {% endwith %}
            {% endif %}
            
            <div class="alert {{ message_class }} alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endwith %}
    {% endfor %}
{% endif %}

<!--
<div class="alert alert-primary" role="alert">
    A simple primary alert—check it out!
</div>
<div class="alert alert-secondary" role="alert">
A simple secondary alert—check it out!
</div>
<div class="alert alert-success" role="alert">
A simple success alert—check it out!
</div>
<div class="alert alert-danger" role="alert">
A simple danger alert—check it out!
</div>
<div class="alert alert-warning" role="alert">
A simple warning alert—check it out!
</div>
<div class="alert alert-info" role="alert">
A simple info alert—check it out!
</div>
<div class="alert alert-light" role="alert">
A simple light alert—check it out!
</div>
<div class="alert alert-dark" role="alert">
A simple dark alert—check it out!
</div> -->