blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("post/<int:id>/", views.post, name="post"),

]

jobs/urls.py
# noqa: D100
from django.urls import path
from . import views
app_name = "jobs"

urlpatterns = [
    path("add/", views.job_add_view, name="add"),
    path("archive/", views.JobArchiveView.as_view(), name="archive"),
    path("delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete"),
    path("download/", views.job_download_view, name="download"),
    path("edit/<int:pk>/", views.job_edit_view, name="edit"),
    path("list/", views.JobListView.as_view(), name="list"),
    path("settings/", views.settings_view, name="settings"),
]

jobs/models.py
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils import timezone

from accounts.models import Profile
from core.models import (
    Country,
    Currency,
    JobFunction,
    LocationPolicy,
    WorkContract,
    PayRate,
)

from core.choices import StatusChoices, SourceChoices

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create your models here.


class Job(models.Model):
    id = models.BigAutoField(primary_key=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    url = models.URLField(blank=True, null=True)
    source = models.CharField(
        max_length=2, choices=SourceChoices.choices(), null=True, blank=True
    )

    job_title = models.CharField(max_length=100, blank=True, null=True)
    job_function = models.ForeignKey(
        JobFunction, on_delete=models.SET_NULL, null=True, blank=True
    )
    description = models.TextField(blank=True, null=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    is_recruiter = models.BooleanField(default=False, null=True, blank=True)

    location_policy = models.ForeignKey(
        LocationPolicy, on_delete=models.SET_NULL, null=True, blank=True
    )
    work_contract = models.ForeignKey(
        WorkContract, on_delete=models.SET_NULL, null=True, blank=True
    )

    min_pay = models.IntegerField(null=True, blank=True)
    max_pay = models.IntegerField(null=True, blank=True)
    pay_rate = models.ForeignKey(
        PayRate, on_delete=models.SET_NULL, null=True, blank=True
    )
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True
    )

    city = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True
    )

    note = models.TextField(null=True, blank=True)
    status = models.CharField(
        max_length=2, choices=StatusChoices.choices(), default=StatusChoices.default()
    )

    applied = models.BooleanField(null=True, blank=True)
    date_applied = models.DateField(null=True, blank=True)

    interviewed = models.BooleanField(null=True, blank=True)
    date_interviewed_set = models.DateField(null=True, blank=True)

    offered = models.BooleanField(null=True, blank=True)
    date_offered_set = models.DateField(null=True, blank=True)

    archived = models.BooleanField(null=True, blank=True, default=False)
    has_been_archived = models.BooleanField(
        null=True, blank=True, default=False)

    def __str__(self):
        return f"{self.company} - {self.job_title}"

    def _update_if_changed(self):
        if self.pk:
            logger.debug("PK exists")
            original = Job.objects.filter(pk=self.pk).first()
            if not original:
                logger.debug("Original does not exist")
                self.updated = timezone.now()
            else:
                logger.debug("Original exists")
                if original.status != self.status or original.note != self.note:
                    logger.debug("Status or note has changed")
                    logger.info("Updating job...")
                    self.updated = timezone.now()

    def _set_applied(self):
        logger.info("Setting applied...")

        try:
            if self.status in StatusChoices.get_applied_statuses():
                logger.info("Job is applied")

                if not self.applied:
                    self.applied = True

                if not self.date_applied:
                    self.date_applied = timezone.now()

            else:
                if self.status == StatusChoices.OPEN[0]:
                    logger.info("Job is not applied")

                    if self.applied:
                        self.applied = False

                    if self.date_applied:
                        self.date_applied = None

        except Job.DoesNotExist:
            pass

    def _set_interviewed(self):
        logger.info("Setting interviewed...")
        if self.status in [StatusChoices.INTERVIEW, StatusChoices.OFFER]:
            self.interviewed = True
            if not self.date_interviewed_set:
                self.date_interviewed_set = timezone.now()

    def save(self, *args, **kwargs):
        self._update_if_changed()
        self._set_applied()
        self._set_interviewed()
        super().save(*args, **kwargs)


class Settings(models.Model):
    """This model represents the job settings for a user."""

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name="job_settings"
    )

    auto_archive = models.BooleanField(null=True, blank=True, default=True)
    archive_after_weeks = models.IntegerField(null=True, blank=True, default=2)

accounts/views/settings.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import Profile
from accounts.forms import UserUpdateForm, ProfileUpdateForm
from accounts.messages import AccountsMessageManager


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
User = get_user_model()


@login_required
def settings_view(request, id):
    """
    A view that handles user profile settings.

    This view renders a form for the user to edit their profile
    settings. If the request is POST, it validates the form and
    saves the changes. If the form is invalid, it redirects to the
    same page with an error message.

    If the request is GET, it renders the form with the user's
    current information.

    Args:
        - request (`django.http.HttpRequest`): The HTTP request object
        - id (`int`): The ID of the profile to be edited

    Returns:
        - `django.http.HttpResponse`: The response object
    """
    # Fetch the profile using the slug
    profile = get_object_or_404(Profile, id=id)

    # Check if the logged-in user owns the profile, otherwise redirect
    if profile.user != request.user:
        messages.error(request, "You are not authorized to view or edit this profile.")
        return redirect("core:home")

    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.save()
            profile = profile_form.save()
            profile.user = user
            profile.save()

            messages.success(request, AccountsMessageManager.profile_update_success)

            return redirect("accounts:profile", id=profile.id)
        else:
            if not profile_form.is_valid():
                errors = profile_form.errors.as_data()
                if errors.get("birth_date"):
                    messages.error(request, AccountsMessageManager.invalid_birth_date)

            messages.error(
                request, f"Invalid form {profile_form.errors} {user_form.errors}"
            )
            return redirect("accounts:profile", id=profile.id)
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=profile)

    context = {
        "user_id": request.user.id,
        "user_form": user_form,
        "profile_form": profile_form,
        "profile": profile,
    }
    return render(request, "accounts/profile_settings.html", context)

apptrack/jobs/views/job_add.py
"""Manages the adding of jobs for the requesting user."""
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from jobs.models import Board
from jobs.forms import JobForm

logger = logging.getLogger(__name__)


@login_required
@require_POST
def job_add_view(request):
    """Handles POST requests to add a new job for the requesting user.

    This view processes the submitted job form data. If the form is valid,
    it saves the job, associates it with the user's profile and board, and
    redirects to the referring URL. The referring URL is obtained from the
    request.POST dictionary, passed as a hidden input field on the add_job_modal.

    Args:
        request (HttpRequest): The request object containing form data.

    Returns:
        HttpResponseRedirect: Redirects to the referring URL. If the form is valid, the 
            response will contain a success message. If the form is invalid, the 
                response will contain an error message.
    """
    board = Board.objects.filter(profile=request.user.profile).first()
    referer_url = request.POST.get("referrer")

    if request.method == "POST":
        form = JobForm(request.POST)

        if form.is_valid():
            job = form.save()
            job.board = board
            job.profile = request.user.profile
            job.save()
            messages.success(request, "Job added successfully!")
        else:
            messages.error(request, f"Failed to add job {form.errors}. \
                           Please try again.")

    return redirect(referer_url)

apptrack/jobs/views/job_archive.py
"""Manages requests to archive jobs."""
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import View

from jobs.models import Job

logger = logging.getLogger(__name__)


class JobArchiveView(LoginRequiredMixin, View):
    """POST only view to archive jobs."""

    def post(self, request, *args, **kwargs):
        """Archives a job.

        This view takes a POST request to archive a job. The job_id is
        expected to be in the request.POST dictionary. The job is set to
        archived = True, and the view redirects to the jobs:board URL.

        Args:
            request (HttpRequest): The request object.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.

        Returns:
            HttpResponseRedirect: The response object.
        """
        logger.debug("Archiving job...")
        job_id = request.POST.get("job_id")
        job = Job.objects.get(id=job_id)

        job.archived = True  # Assuming `is_archived` is a boolean field
        job.save()
        logger.debug("Job %s archived", job_id)
        return redirect("jobs:board")

apptrack/jobs/views/job_assign.py
"""Manages the assignment of jobs to columns. In the job board view."""
import logging

from django.contrib.auth import get_user_model

from rest_framework.response import Response
from rest_framework.views import APIView

from jobs.models import Column, Job

logger = logging.getLogger(__name__)

User = get_user_model()


class JobAssignView(APIView):
    """Manages the assignment of jobs to columns.

    This class view manages the assignment of jobs to columns in the job board view.
    It handles POST requests. APIView is used to provide a Response object.
    """

    def post(self, request, *args, **kwargs):
        """Handles POST requests for the assignment of a job to a column.

        This function manages the assignment of a job to a column in the job board view.
        It handles POST requests and assigns the job to the column specified by the
        url parameter 'col_id' and the job specified by the url parameter 'job_id'.

        Args:
            request (HttpRequest): The request object.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.
                'col_id' (int): The ID of the column to assign the job to.
                'job_id' (int): The ID of the job to assign to the column.

        Returns:
            Response: The response object.
        """
        logger.debug("Assigning job...")
        col_id = kwargs["col_id"]
        job_id = kwargs["job_id"]

        column = Column.objects.get(id=col_id)
        job = Job.objects.get(id=job_id)

        job.column = column
        logger.debug("Job assigned to column %s", column)

        job.save()
        column.save()
        logger.debug("Job saved successfully to column: %s", column)

        data = {"job_status": job.status, "job_id": job.id}
        return Response(data)

apptrack/jobs/views/job_delete.py
"""Manages the job delete view for the requesting user."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import View

from jobs.models import Job


class JobDeleteView(LoginRequiredMixin, SuccessMessageMixin, View):
    """Manages the job delete view for the requesting user.

    If the request method is POST, it deletes the job and redirects to the job board.
    If the request method is GET, it redirects to the core home page.
    """
    model = Job
    success_url = reverse_lazy("jobs:board")
    success_message = "Job deleted successfully"

    def get(self, request, *args, **kwargs):  # noqa: D102
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):  # noqa: D102
        job = self.model.objects.get(id=kwargs["pk"])
        job.delete()
        return redirect(reverse("core:home"))

apptrack/jobs/views/job_download.py
"""This module processes the job download view.

Manages the job download view for the requesting user. Allowing them to download a CSV 
file of their jobs based on a provided date range.
"""

import csv

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from jobs.forms import DownloadJobsForm
from jobs.models import Job


@login_required
def job_download_view(request):
    """Manages the job download view for the requesting user.

    Allows the user to download a CSV file of their jobs based on a provided date range.
    If the request method is GET, it renders a form for the user to input the date 
    range. If the request method is POST, it generates a CSV file with the jobs in the 
    specified date range and returns it as a response.

    The CSV file will have the following columns: ID, Job Title, Company, URL, Status,
    and Updated.

    Args:
        request: The current request

    Returns:
        HttpResponse: A CSV file with the jobs in the specified date range if the 
            request method is POST, or a form for the user to input the date range if 
                the request method is GET
    """
    if request.method == "GET":
        form = DownloadJobsForm()
        return render(
            request,
            "jobs/download_jobs.html",
            {"form": form, "user_id": request.user.id},
        )

    # Handle POST request (CSV file generation)
    start_date = request.POST.get("start_date")
    end_date = request.POST.get("end_date")

    # Filter jobs based on the `updated` field
    jobs = Job.objects.filter(updated__range=(
        start_date, end_date)).order_by("id")

    filename = f"jobs_{start_date}_{end_date}.csv"
    # Prepare the response
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )

    # Write the CSV file
    writer = csv.writer(response)
    writer.writerow(
        ["ID", "Job Title", "Company", "URL", "Status", "Updated"]
    )  # CSV headers

    for job in jobs:
        writer.writerow(
            [
                job.id,
                job.job_title,
                job.company,
                job.url,
                job.get_status_display(),
                job.updated,
            ]
        )

    return response

apptrack/jobs/views/task_edit.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from jobs.models import InterviewTask


@login_required
@require_POST
def task_edit_view(request, id):
    if request.method == "POST":
        task = InterviewTask.objects.get(id=id)
        is_completed = json.loads(request.body)['completed']
        if is_completed == "true":
            task.is_completed = True
        else:
            task.is_completed = False
        task.save()
        return HttpResponse(status=200)

jobs/templates/jobs/base.html
<!DOCTYPE html>

{% extends 'core/base_authenticated.html' %}

<head>
    {% block title %}
        {% block subtitle %}
        {% endblock %}
    {% endblock %}
    {% block css %}
        {% block page_css %}
        {% endblock %}
    {% endblock %}
</head>

{% block content %}
    <nav class="navbar navbar navbar-expand-md navbar-light px-3">
        
        <!-- Toggler/collapsible Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav w-100">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/jobs/list/' %}active{% endif %}" href="{% url 'jobs:list' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/jobs/download/' %}active{% endif %}" href="{% url 'jobs:download' %}">Download Report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/jobs/settings/' %}active{% endif %}" href="{% url 'jobs:settings' %}">Settings</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block page_content %}
    {% endblock %}
    
    
{% endblock %}

jobs/templates/jobs/board.html
<!DOCTYPE html>

{% extends 'jobs/base.html' %}

{% block page_content %}

{% load static %}
{% load filter %}
{% csrf_token %}
<head>{% block subtitle %}<title>Jobs | Board</title>{% endblock %}</head>
<meta name="csrf-token" content="{{ csrf_token }}">

<link rel="stylesheet" href="{% static 'jobs/styles/kanban.css' %}" />
<script src="{% static 'jobs/scripts/jquery.js' %}" defer></script>
<script src="{% static 'jobs/scripts/kanban.js' %}" defer></script>
<script src="{% static 'jobs/scripts/modalReferal.js' %}"></script>

<div class="container-fluid py-3">
    <div class="row">
        <div class="col">
            <h1 class="text-start">{{ board.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="button" class="btn btn-primary" id="addJobButton" data-bs-toggle="modal" data-bs-target="#addJobModal">
                Add Job
            </button>
        </div>
    </div>

    <div class="row board mt-5">
        <div class="lanes d-flex flex-nowrap py-3 justify-content-between">
            {% for column in columns %}
                <div class="swim-lane card mx-2 {{ column.name|lower }}" id="{{ column.id }}">
                    <div class="card-header p-2 text-center text-truncate {{ column.name|lower }}">
                        <h2 class="{{ column.name|lower }}">{{ column.name }}</h2>
                    </div>
                    <div class="card-body p-0 justify-content-center {{ column.name|lower }}">

                        {% for job in jobs|column_jobs:column %}
                            <div class="task m-2 card align-content-center job-card" draggable="true" id="{{ job.id }}">
                                <div class="card-body py-0 px-1 job-card">
                                    <div class="d-flex justify-content-between align-items-start job-detail">
                                        <!-- Job details -->
                                        <div class="list-group list-group-flush me-auto job-detail">
                                            {% if job.job_title and job.job_title != 'None' %}
                                            <div class="list-group-item text-truncate">
                                                {{ job.job_title }}
                                            </div>
                                            {% endif %}
                                            {% if job.company and job.company != 'None' %}
                                            <div class="list-group-item text-truncate">
                                                {{ job.company }}
                                            </div>
                                            {% endif %}
                                            {% if job.city and job.city != 'None' %}
                                            <div class="list-group-item text-truncate">
                                                {{ job.city }}
                                            </div>
                                            {% endif %}
                                        </div>

                                        <!-- Move the 'a' tag to the top-right -->
                                        <a href="#" class="btn p-0 ms-auto job-detail" data-bs-toggle="modal" data-bs-target="#jobDetailModal{{ job.id }}">
                                            <i class="bi bi-three-dots"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>


{% include 'jobs/modals/detail.html' %}
{% include 'jobs/modals/add.html' %}
{% include 'jobs/modals/edit.html' %}
{% include 'jobs/modals/delete.html' %}
{% include 'jobs/modals/archive.html' %}


{% endblock %}

jobs/templates/jobs/list.html
<!DOCTYPE html>
{% extends 'jobs/base.html' %}
{% load static %}
{% block page_content %}
<head>{% block subtitle %}<title>Jobs | List</title>{% endblock %}</head>
{% block page_css %}
    <style>
        .btn-outline-primary {
    border: none;
    }
    .header-col {
        padding: 0;
    }
    </style>
{% endblock %}
<div class="container-fluid py-3">
    <div class="row">
        <div class="col">
            <h1>Job List</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="button" class="btn btn-primary" id="addJobButton" data-bs-toggle="modal" data-bs-target="#addJobModal">
                Add Job
            </button>
        </div>
        <div class="col">
            <button type="button" class="btn btn-primary" id="filterButton" data-bs-toggle="modal" data-bs-target="#filterModal">
                Filter
            </button>
        </div>
    </div>

    <div class="row py-3">
        <div class="col">
            <div class="list-group list-group-action">
                <div class="list-group-item">
                    <div class="row">
                        <div class="col header-col">
                            <a class="btn btn-outline-primary" href="?ordering={% if ordering == 'job_title' %}-job_title{% else %}job_title{% endif %}">
                                <strong>Job Title</strong>
                                {% if ordering == 'job_title' %}▲{% elif ordering == '-job_title' %}▼{% endif %}
                            </a>
                        </div>
                        <div class="col header-col">
                            <a class="btn btn-outline-primary" href="?ordering={% if ordering == 'company' %}-company{% else %}company{% endif %}">
                                <strong>Company</strong>
                                {% if ordering == 'company' %}▲{% elif ordering == '-company' %}▼{% endif %}
                            </a>
                        </div>
                        <div class="col header-col">
                            <a class="btn btn-outline-primary" href="?ordering={% if ordering == 'status' %}-status{% else %}status{% endif %}">
                                <strong>Status</strong>
                                {% if ordering == 'status' %}▲{% elif ordering == '-status' %}▼{% endif %}
                            </a>
                        </div>
                        <div class="col header-col">
                            <a class="btn btn-outline-primary" href="?ordering={% if ordering == 'city' %}-city{% else %}city{% endif %}">
                                <strong>Location</strong>
                                {% if ordering == 'city' %}▲{% elif ordering == '-city' %}▼{% endif %}
                            </a>
                        </div>
                        <div class="col header-col">
                            <a class="btn btn-outline-primary" href="?ordering={% if ordering == 'archived' %}-archived{% else %}archived{% endif %}">
                                <strong>Archived</strong>
                                {% if ordering == 'archived' %}▲{% elif ordering == '-archived' %}▼{% endif %}
                            </a>
                        </div>
                        <div class="col">
                            <a class="btn btn-outline-primary disabled" href="#">
                                <strong>Actions</strong>
                            </a>
                        </div>
                    </div>
                </div>
                {% for job in jobs %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col">
                                {{ job.job_title }}
                            </div>
                            <div class="col">
                                {{ job.company }}
                            </div>
                            <div class="col">
                                {{ job.get_status_display }}
                            </div>
                            <div class="col">
                                {% if job.city or job.region or job.country %}
                                {% if job.city %}
                                    {{ job.city }}
                                {% endif %}
                                {% if job.region and job.city %}
                                    ,{{ job.region }}
                                {% elif job.region %}
                                    {{ job.region }}
                                {% endif %}
                                {% if job.country and job.region %}
                                    ,{{ job.get_country_display }}
                                {% elif job.country and job.city %}
                                    ,{{ job.get_country_display }}
                                {% elif job.country %}
                                    {{ job.get_country_display }}
                                {% endif %}
                                {% else %}
                                -
                                {% endif %}
                            </div>
                            <div class="col">
                                {{ job.archived }}
                            </div>
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#jobDetailModal{{ job.id }}">
                                            View
                                        </button>
                                    </div>
                                    {% if not job.applied and job.url %}
                                    <div class="col">
                                        <a href="{{ job.url }}" target="_blank" class="btn btn-primary">Apply</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col">
                                No jobs found.
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if page_obj.paginator.num_pages > 1 %}
        <div class="row">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center align-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&lsaquo;</a>
                    </li>
                    {% endif %}

                    {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="page-item active"><span class="page-link">{{ page }}</span></li>
                        {% elif page <= page_obj.number|add:9 and page >= page_obj.number|add:-9 %}
                            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">&rsaquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    {% endif %}
</div>
{% include 'jobs/modals/detail.html' %}
{% include 'jobs/modals/add.html' %}
{% include 'jobs/modals/edit.html' %}
{% include 'jobs/modals/delete.html' %}
{% include 'jobs/modals/archive.html' %}
{% include 'jobs/modals/filter.html' %}

{% endblock %}